baseConfig: 
  cuda: True
  do_train: True
  og_step: 1000
  save_step: 10000
  valid_step: 10000


hyper_graph_noise_01: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_noise_02: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0001
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.01
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False


hyper_graph_noise_03: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_noise_04: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.001
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.01
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False


hyper_graph_noise_05: 
  batch_size: 2048
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0001
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.5
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [50,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_noise_06: 
  batch_size: 2048
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.00005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.5
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False


hyper_graph_noise_07: 
  batch_size: 2048
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0001
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.5
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [50,15]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_noise_08: 
  batch_size: 2048
  name: MLP
  gamma: 10
  dim: 200
  lr: 0.0001
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.5
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [50,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_noise_09: 
  batch_size: 2048
  name: MLP
  gamma: 10
  dim: 700
  lr: 0.0001
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 3000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.5
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [50,15]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False


hyper_graph_edge_size_01: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_edge_size_02: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [20,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_edge_size_03: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [10,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_edge_size_04: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [5,10]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False


hyper_graph_edge_size_05: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,8]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_edge_size_06: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,5]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_edge_size_07: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,3]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False

hyper_graph_edge_size_08: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,1]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False


hyper_graph_small_data_set: 
  batch_size: 1024
  name: MLP
  gamma: 10
  dim: 500
  lr: 0.0005
  box_lr: 0.005
  cuda: True
  decay: 0.1
  max_step: 4000
  layer: 2
  n_size: 400
  test_step: 50
  reg_weight: 0.001
  dropout: 0.3
  margin: 0.2
  cl_temp: 1.0
  neibor_size: [30,1]
  full_neibor_size: [50,15]
  test_neibor_size: [50,15]
  data_reverse: False
  node_gnn_layer: 3
  node_gnn_dropout: 0.6
  gamma_s: 10
  gamma_t: 10
  transformer_dim: 200
  transformer_layer: 4
  cl_weight: 0.0001
  noise_weight: 0.05
  noise_sigma: 0.01
  add_edge_noise: False
  add_entity_noise: False
  add_edge_cl: False